// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7EZDhMUQi1popsrQCFvO8N0U57Igjvo',
    appId: '1:54282229231:web:77b15e591f4d3b579b921a',
    messagingSenderId: '54282229231',
    projectId: 'notasapp-b436a',
    authDomain: 'notasapp-b436a.firebaseapp.com',
    storageBucket: 'notasapp-b436a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpz2W3gbpxgpZ4ZDTK8E14kHMoHIsYosc',
    appId: '1:54282229231:android:748b70bb1e8f28489b921a',
    messagingSenderId: '54282229231',
    projectId: 'notasapp-b436a',
    storageBucket: 'notasapp-b436a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJXTCxlU-osynaFYnVsvHD912DxDupMw',
    appId: '1:54282229231:ios:189c5edb1cf545719b921a',
    messagingSenderId: '54282229231',
    projectId: 'notasapp-b436a',
    storageBucket: 'notasapp-b436a.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVJXTCxlU-osynaFYnVsvHD912DxDupMw',
    appId: '1:54282229231:ios:189c5edb1cf545719b921a',
    messagingSenderId: '54282229231',
    projectId: 'notasapp-b436a',
    storageBucket: 'notasapp-b436a.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ7EZDhMUQi1popsrQCFvO8N0U57Igjvo',
    appId: '1:54282229231:web:7c9df7ce25948c8b9b921a',
    messagingSenderId: '54282229231',
    projectId: 'notasapp-b436a',
    authDomain: 'notasapp-b436a.firebaseapp.com',
    storageBucket: 'notasapp-b436a.firebasestorage.app',
  );

}